export const tokens = {
  colors: {
    sidebar: {
      bg: '#0d0f14',
      surface: '#13161e',
      border: '#1e2130',
      hover: '#1a1d28',
      active: '#1f2235',
      text: '#94a3b8',
      textActive: '#f1f5f9',
      textMuted: '#4b5563',
    },
    canvas: {
      bg: '#f5f6fa',
      card: '#ffffff',
      border: '#e4e7ef',
      borderSubtle: '#eef0f6',
    },
    accent: {
      default: '#6366f1',
      hover: '#4f46e5',
      subtle: '#eef2ff',
      muted: '#c7d2fe',
      foreground: '#ffffff',
    },
    status: {
      success: '#22c55e',
      successBg: '#f0fdf4',
      successText: '#15803d',
      warning: '#f59e0b',
      warningBg: '#fffbeb',
      warningText: '#b45309',
      error: '#ef4444',
      errorBg: '#fef2f2',
      errorText: '#b91c1c',
      info: '#3b82f6',
      infoBg: '#eff6ff',
      infoText: '#1d4ed8',
      muted: '#64748b',
    },
  },
  spacing: {
    sidebarWidth: '248px',
    topbarHeight: '56px',
    contentPadding: '24px',
    cardPadding: '20px',
    sectionGap: '20px',
  },
  radius: {
    sm: '6px',
    md: '8px',
    lg: '12px',
    xl: '16px',
  },
  shadows: {
    card: '0 1px 3px 0 rgba(0,0,0,0.06), 0 1px 2px -1px rgba(0,0,0,0.04)',
    cardMd: '0 4px 12px 0 rgba(0,0,0,0.08), 0 1px 3px -1px rgba(0,0,0,0.04)',
    cardLg: '0 8px 24px 0 rgba(0,0,0,0.10), 0 2px 6px -2px rgba(0,0,0,0.05)',
  },
  typography: {
    sizes: {
      xs: '11px',
      sm: '12px',
      base: '13px',
      md: '14px',
      lg: '16px',
      xl: '18px',
      '2xl': '20px',
      '3xl': '24px',
      '4xl': '30px',
    },
    weights: {
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
  },
} as const

export type StatusVariant = 'success' | 'warning' | 'error' | 'info' | 'muted' | 'draft' | 'active' | 'archived'

export const statusVariantMap: Record<string, StatusVariant> = {
  active: 'success',
  published: 'success',
  success: 'success',
  ready: 'success',
  draft: 'draft',
  pending: 'muted',
  in_review: 'info',
  approved: 'info',
  scheduled: 'info',
  processing: 'warning',
  importing: 'warning',
  warning: 'warning',
  failed: 'error',
  error: 'error',
  archived: 'archived',
  disconnected: 'error',
  expired: 'warning',
}
